language: python
sudo: false
cache: pip
python:
  - "2.7.6"
  #- "3.5"
  #- "3.4"
  #- "3.3"
services:
  - memcached
env:
  matrix:
    #- DJANGO="Django<1.7,>=1.8"
    #- DJANGO="Django<1.9,>=1.8"
    - DJANGO="Django<1.10,>=1.9"
    - DJANGO="-e git+https://github.com/django/django.git@master#egg=Django"
matrix:
  fast_finish: true
  allow_failures:
    - env: DJANGO="-e git+https://github.com/django/django.git@master#egg=Django"
install:
  - pip install --upgrade pip
  - pip install -r requires_test.txt
  - pip install $DJANGO
  - pip install --upgrade coveralls
script:
  - py.test --cov-report term-missing --cov=django_tml tests
after_success:
  - coveralls
