language: python
sudo: false
cache: pip
python:
  - "2.7"
  #- "3.5"
  #- "3.4"
  #- "3.3"
services:
  - memcached
env:
  - DJANGO_VERSION=Django==1.7.11
  - DJANGO_VERSION=Django==1.8.8
  - DJANGO_VERSION=Django==1.9.1
  - DJANGO_VERSION="-e git+https://github.com/django/django.git@master#egg=Django"
matrix:
  fast_finish: true
  allow_failures:
    - env: DJANGO_VERSION="-e git+https://github.com/django/django.git@master#egg=Django"
install:
  - pip install --upgrade pip
  - pip install -r requires_test.txt
  - pip install tml[pylibmc,memcached]>=0.2.6
  - pip install -q $DJANGO_VERSION
  - pip install --upgrade coveralls
script:
  - py.test --cov-report term-missing --cov=django_tml tests
after_success:
  - coveralls
